version: '3.8'

services:

  # SSL
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '443:443'
    links:
      - app
    restart: always
    volumes:
      - ./container/https-portal/ssl_certs:/var/lib/https-portal
    environment:
      DOMAINS:
        'www.dev-simple-lamp.local -> http://app:80, admin.dev-simple-lamp.local -> http://app:80'
      STAGE: 'local' # Don't use production until staging works
      #FORCE_RENEW: 'true'

  # Application
  app:
    build:
      context: .
      dockerfile: ./container/app/Dockerfile
    ports:
      - "80:80"
    working_dir: /usr/src/application
    volumes:
      - ./application:/usr/src/application
    environment:
      TZ: JST-9
    depends_on:
      - db
      - maildev

  # DB
  db:
    build:
      context: .
      dockerfile: ./container/db/Dockerfile
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./container/db/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: example
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: JST-9

  # DB GUI
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      TZ: JST-9
    depends_on:
      - db

  # Mail
  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
      - "25:25"
    expose:
      - "80"
      - "25"
    command: bin/maildev --web 80 --smtp 25
    environment:
      TZ: JST-9