version: '3.8'

services:

  # Application
  app:
#    container_name: sl-app
    build:
      context: .
      dockerfile: ./container/app/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    working_dir: /usr/src/application
    volumes:
      - ./application:/usr/src/application
    environment:
      TZ: JST-9
    depends_on:
      - db
      - maildev

  # DB
  db:
#    container_name: sl-db
    build:
      context: .
      dockerfile: ./container/db/Dockerfile
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./container/db/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: example
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: JST-9

  # DB GUI
  adminer:
#    container_name: sl-adminer
    image: adminer
    ports:
      - "8080:8080"
    environment:
      TZ: JST-9
    depends_on:
      - db

  # Mail
  maildev:
#    container_name: sl-maildev
    image: djfarrelly/maildev
    ports:
      - "1080:80"
      - "25:25"
    expose:
      - "80"
      - "25"
    command: bin/maildev --web 80 --smtp 25
    environment:
      TZ: JST-9