#!/bin/bash

set -e # fail on any error

HOST_NAME="app"
# TODO: your application path.
APP_NAME="xxxxxx"
APP_PATH="/usr/src/application/${APP_NAME}"

case "$1" in
  "up" )
    eval "docker-compose up"
    ;;
  "build" )
    eval "docker-compose build"
    ;;
  "restart" )
    eval "docker-compose restart"
    ;;
  "login" )
    eval "docker-compose exec ${@:2} /bin/bash"
    ;;
  "command" )
    APP_NAME=${@:2}
    echo "----------------------------"
    echo "[$APP_NAME] waiting for command input..."
    read input
    eval "docker-compose exec $APP_NAME $input"
    ;;
esac