#!/bin/bash

set -e # fail on any error

APP_NAME="sl-app"
# TODO: your application path.
APP_PATH="/usr/src/application/"

case "$1" in
  "up" )
    eval "docker-compose up"
    ;;
  "build" )
    eval "docker-compose build"
    ;;
  "restart" )
    eval "docker-compose restart"
    ;;
  "login" )
    eval "docker-compose exec ${@:2} /bin/bash"
    ;;
  "container_restart" )
    eval "docker restart ${@:2}"
    ;;
  "command" )
    # ex) ./manage command sl-app
    APP_NAME=${@:2}
    echo "----------------------------"
    echo "[$APP_NAME] waiting for command input..."
    read input
    eval "docker-compose exec $APP_NAME $input"
    ;;
  "composer" )
    eval "docker-compose exec $APP_NAME /bin/bash -c 'cd $APP_PATH && composer ${@:2}'"
    ;;
  "npm" )
    eval "docker-compose exec $APP_NAME /bin/bash -c 'cd $APP_PATH && npm ${@:2}'"
    ;;
  "node" )
    eval "docker-compose exec $APP_NAME /bin/bash -c 'cd $APP_PATH && node ${@:2}'"
    ;;
esac